services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass test
    ports:
      - 6379:6379

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
