services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - curious

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - curious

networks:
  curious:
    driver: bridge
